name: OpenApiSpexYaml

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: [self-hosted, Linux]

    env:
      MIX_ENV: test
      ImageOS: ubuntu20

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@c428d8c359c7a208a7471729c4a619c35780d541
        with:
          elixir-version: "1.13.3" # Define the elixir version [required]
          otp-version: "24.3" # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - run: mix deps.get
      - run: mix deps.unlock --check-unused
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix test
